<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PinkRooster.Samples\PinkRooster.Samples.csproj" />
    <ProjectReference Include="..\..\src\PinkRooster.ToolCollections.Mcp\PinkRooster.ToolCollections.Mcp.csproj" />
  </ItemGroup>

</Project>
